name: build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
          - os: ubuntu-latest
            runtime: linux-x64
          - os: ubuntu-latest
            runtime: linux-arm64
          - os: macos-latest
            runtime: osx-arm64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: |
        dotnet publish "MultiPlatformFun/MultiPlatformFun.csproj" -o ${{ github.workspace }}/publish -r ${{ matrix.runtime }} -p:PublishSingleFile=true --self-contained true
        
